#!/usr/bin/env python
import os
import sys


def get_env_variables():
    return os.environ


def get_input():
    if len(sys.argv)==1 or sys.argv[1] == '-':
        return "\n".join(sys.stdin.readlines())
    with open(sys.argv[1], 'r') as f:
        return f.read()


def get_required_variables(str):
    """
    >>> get_required_variables('${ONE} $TWO ${THREE} FOUR ${FIVE}')
    ['ONE', 'THREE', 'FIVE']
    """
    return [x[:x.find('}')] for x in str.split('${')[1:]]

if __name__ == '__main__':
    input = get_input()
    env_variables = get_env_variables()
    required_variables = get_required_variables(input)
    for v in required_variables:
        assert v in env_variables, \
            '"' + v + '" is required but not found in envrionment variables.'
    output = input
    for v in required_variables:
        output = output.replace('${' + v + '}', env_variables[v])
    sys.stdout.write(output)
    sys.stdout.flush()
